const DATA_URL = 'https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/renderer-specific/adbds.csv';
const state = {};
let chart;
function uniq(a){ return [...new Set(a.filter(v => v !== undefined && v !== null && v !== ''))].sort((x,y)=>String(x).localeCompare(String(y), undefined, {numeric:true})); }
function mean(vals){ vals = vals.map(Number).filter(Number.isFinite); return vals.length ? vals.reduce((a,b)=>a+b,0)/vals.length : null; }
function el(tag, attrs={}, text=''){ const e=document.createElement(tag); Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v)); if(text) e.textContent=text; return e; }
function select(label, values, value){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const s=el('select'); values.forEach(v=>{const o=el('option',{value:v},v); if(v===value) o.selected=true; s.append(o);}); w.append(s); return [w,s]; }
function input(label, value=''){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const i=el('input',{type:'number', value}); w.append(i); return [w,i]; }
function table(rows, cols){ return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td>${r[c] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
function participantNote(rows, allRows){ const ids=uniq(rows.map(d=>d.USUBJID)); const total=uniq(allRows.map(d=>d.USUBJID)).length; return `${ids.length} of ${total} participants shown (${total ? (100*ids.length/total).toFixed(1) : '0.0'}%).`; }

d3.csv(DATA_URL).then(data => { const measures=uniq(data.map(d=>d.TEST)), visits=uniq(data.map(d=>d.VISITN)); const app=document.getElementById('app'); app.innerHTML='<div class="controls"></div><div class="note" id="note"></div><div class="chartBox"><canvas id="chart"></canvas></div><div class="listing" id="listing"></div>'; const controls=app.querySelector('.controls'); const [xW,xS]=select('X Measure',measures,measures[0]), [yW,yS]=select('Y Measure',measures,measures[1]), [bW,bS]=select('Baseline Visit',visits,visits[0]), [cW,cS]=select('Comparison Visit',visits,visits.at(-1)), [aW,aS]=select('Treatment Group',['All',...uniq(data.map(d=>d.ARM))],'All'); controls.append(xW,yW,bW,cW,aW); [xS,yS,bS,cS,aS].forEach(x=>x.onchange=render); function delta(id,m){const rows=data.filter(d=>d.USUBJID===id&&d.TEST===m&&d.STRESN&&d.VISITN&&(aS.value==='All'||d.ARM===aS.value)); const b=rows.find(d=>d.VISITN===bS.value), c=rows.find(d=>d.VISITN===cS.value); return b&&c?+c.STRESN-+b.STRESN:null;} function render(){ const ids=uniq(data.map(d=>d.USUBJID)); const pts=ids.map(id=>({id,x:delta(id,xS.value),y:delta(id,yS.value)})).filter(d=>Number.isFinite(d.x)&&Number.isFinite(d.y)); document.getElementById('note').textContent=`${pts.length} participants shown.`; if(chart)chart.destroy(); chart=new Chart(document.getElementById('chart'),{type:'scatter',data:{datasets:[{label:'Delta-delta',data:pts,backgroundColor:'#7c3aed'}]},options:{plugins:{title:{display:true,text:'Change-from-baseline comparison'},tooltip:{callbacks:{label:c=>`${c.raw.id}: x Δ${c.raw.x.toFixed(1)}, y Δ${c.raw.y.toFixed(1)}`}}},scales:{x:{title:{display:true,text:`Δ ${xS.value}`}},y:{title:{display:true,text:`Δ ${yS.value}`}}},onClick:(e,a)=>{if(a.length)document.getElementById('listing').innerHTML=table([pts[a[0].index]],['id','x','y']);}}});} render(); });
